spring:
  application:
    name: devmountain
  datasource:
    url: jdbc:postgresql://localhost:5432/devmountain
    username: postgres
    password: 5t6y7u8i!
    hikari:
      maximum-pool-size: 20
  jpa:
    hibernate:
      ddl-auto: create
    properties:
      hibernate:
        dialect: org.hibernate.dialect.PostgreSQLDialect


  security:
    oauth2:
      client:
        registration:
          google:
            client-id: ${GOOGLE_ID}
            client-secret: ${GOOGLE_SECRET}
            #            OAuth2 오류 401: invalid_client flowName=GeneralOAuthFlow 해결
            redirect-uri : "https://{baseHost}{basePort}/login/oauth2/code/google"
            scope:
              - profile
              - email

          naver:
            client-id: ${NAVER_ID}
            client-secret: ${NAVER_SECRET}
            client-name: Naver
            authorization-grant-type: authorization_code
            redirect-uri: "https://{baseHost}{basePort}/login/oauth2/code/naver"
            scope:
              - name
              - email
              - profile_image

        # provider 정보 정의
        provider:
          naver: # ← provider-id 와 동일한 key
            authorization-uri: https://nid.naver.com/oauth2.0/authorize
            token-uri: https://nid.naver.com/oauth2.0/token
            user-info-uri: https://openapi.naver.com/v1/nid/me
            user-name-attribute: response

  brave:
    api:
      key: BSAANNiVuNo0_p55Y01c12_NbQvQzhj

  toss:
    secret-key: test_sk_GjLJoQ1aVZPDMqQAqkpJ8w6KYe2R
    confirm-url: https://api.tosspayments.com/v1/payments/confirm



  ai:
    openai:
      api-key: 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
      base-url: https://api.openai.com
      chat:
        options:
          model: gpt-4o-mini
      embedding:
        model: text-embedding-3-small