services:
  redis:
    image: redis:7.2
    container_name: devmountain-redis
    ports:
      - "${REDIS_PORT}:6379"

  postgres:
    image: ankane/pgvector:latest
    container_name: devmountain-postgres
    ports:
      - "${POSTGRES_PORT}:5432"
    environment:
      POSTGRES_PASSWORD: ${POSTGRES_PASSWORD}
      POSTGRES_DB: ${POSTGRES_DB}
    volumes:
      - devmountain-postgres-volume:/var/lib/postgresql/data

#  app:
#    build:
#      context: .
#      dockerfile: Dockerfile
#    container_name: devmountain-app
#    ports:
#      - "${APP_PORT}:8080"
#    environment:
#      SPRING_PROFILES_ACTIVE: prod
#      REDIS_HOST: redis
#      POSTGRES_HOST: postgres
#      POSTGRES_DB: ${POSTGRES_DB}
#      POSTGRES_PASSWORD: ${POSTGRES_PASSWORD}
#    depends_on:
#      - redis
#      - postgres

volumes:
  devmountain-postgres-volume:
