services:
  redis:
    image: redis:7.2
    container_name: devmountain-redis
    ports:
      - "${REDIS_PORT}:6379"
    networks:
      - devmonntain-net

  postgres:
    image: ankane/pgvector:latest
    container_name: devmountain-postgres
    ports:
      - "${POSTGRES_PORT}:5432"
    environment:
      POSTGRES_PASSWORD: ${POSTGRES_PASSWORD}
      POSTGRES_DB: ${POSTGRES_DB}
    volumes:
      - devmountain-postgres-volume:/var/lib/postgresql/data
    networks:
      - devmonntain-net

  app:
    build:
      context: .
      dockerfile: Dockerfile
    container_name: devmountain-app
    ports:
      - "${APP_PORT}:8080"
    environment:
      SPRING_PROFILES_ACTIVE: prod
      REDIS_HOST: redis
      POSTGRES_HOST: postgres
      POSTGRES_DB: ${POSTGRES_DB}
      POSTGRES_PASSWORD: ${POSTGRES_PASSWORD}
    depends_on:
      - redis
      - postgres
    networks:
      - devmonntain-net

volumes:
  devmountain-postgres-volume:

networks:
  devmonntain-net:
    name: devmonntain-net # 네트워크 명시를 해놔서 각 컨테이너에서 networks를 선언할 필요는 없지만 compose는 명시적으로 적어두는게 좋다고 권장함.
    driver: bridge
