name: CI - Build and Test

on:
  push:
    branches:
      - "main"
      - "dev"

jobs:
  build:
    runs-on: ubuntu-latest

    steps:
      - uses: actions/checkout@v3

      - name: Set up JDK
        uses: actions/setup-java@v3
        with:
          java-version: '17'
          distribution: 'corretto'

      - name: Build
        run: ./gradlew clean build -x test

      - name: Run Tests
        run: ./gradlew test